### ISSUE TITLE
update/deprecate the downloads page

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint.github.io#104]
What are we doing with all the binaries?

Proposal:
tendermint - should be downloadable from RTD
abci-cli - should be downloadable from t-mint RTD (?)
basecoin - deprecated/whatever emerges from cosmos-sdk will be downloadable from sdk docs
ethermint - should be downloadable from ethermint RTD
merkleeyes - deprecated in favour of iavl - no binary required (?)

**Comment by jolesbi** [comment]
@zramsay @nylira i agree the binaries should be downloadable from read the docs (and github — right?). i'm in favour of removing the downloads page from Tendermint unless they can be dynamically updated. let's make a call on this.

**Comment by nylira** [comment]
The downloads page on tendermint.com makes it really easy to download binaries in two clicks. Finding a download link in RTD is more complicated. Right now the Tendermint RTD page even links to tendermint.com/download. I don't think burying the download link in the docs is going to improve accessibility.

Basecoin should be removed, and for merkleyes -> iavl: should we link to the iavl binary?

**Comment by nylira** [comment]
@zramsay are there download pages on RTD for Cosmos SDK, Ethermint, and Tendermint? If so, we can keep the download page and link to them.

**Comment by zramsay** [comment]
they don't have download pages per se, but the install instructions ought to be something like:

```
curl theBinary
untar/upzip theBinary
mv theBinary
chmod +x theBinary
```

**Comment by jolesbi** [comment]
can we use the release pages on github? that seems like an OK place to store download info. @nylira i'd rather link there instead of having to update tendermint.com/downloads every time there is a release...

**Comment by nylira** [comment]
@jolesbi yeah let's use the release pages. Saves us some effort. I'll make the PR.
