### ISSUE TITLE
Update the link to TMChat

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint.github.io#43]
This [site](https://tendermint.com/docs/guides/app-architecture) points to wolfpsd repo and should probably be updated to point to https://github.com/jTendermint/jabci

tags: docs, low_hanging_fruit

**Comment by nylira** [comment]
jabci is not TMChat though?

**Comment by adrianbrink** [comment]
That's correct. Strange I must have gotten the pages confused. I thought I saw somewhere that we were pointing to the wrong thing. If I find it again I'll fix it :-)
