### ISSUE TITLE
Explain Tendermint better

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint.github.io#5]
You know how Apache Web Server sits in front of Wordpress, and talks to Wordpress via fastcgi?

[12:31]  
They both combine into one server-side process that handle connection logic, like throttling and security.

[12:31]  
Tendermint is like Apache Web Server for distributed ledgers.  It handles things like P2P networking, BFT consensus, transaction broadcasting.

[12:32]  
It’s agnostic to any business logic processing of transactions… to Tendermint they just look like binary bytes.  You plug in a program that processes the raw Tx bytes.

[12:33]  
Once the network of validators (via TendermintCore) agree on a block, and commit it, the txs get pushed into the application.

[12:33]  
via TMSP, a network socket protocol that is analogous to fastcgi in the ApacheWebServer+Wordpress example.

**Comment by zramsay** [comment]
can be closed in favour of https://github.com/tendermint/tendermint/issues/543
