### ISSUE TITLE
Suggestions for beginner path

### ISSUE THREAD

**Issue by joshkestenberg** [tendermint/tendermint.github.io#50]
1) Brief information segment on all comp-sci subjects mentioned in the introduction. They're easy to explain, but difficult to research --- distributed systems, state replication, consensus, fault tolerance/BFT, Blockchain Tech.

2) A step-by-step explanation of how the ABCI functions similar to the one in this video (http://www.youtube.com/watch?v=9krAQzN6tbc&t=23m16s) from the start time I’ve linked until 25:50. I actually think the main docs would benefit from something like this as well.

3) Tips to get up and running with a gRPC app: brief explanations of Protobuf and Remote Procedure Call, and what they mean in the context of the Tendermint architecture. Also, having something like the "Message Types" section from this readme (https://github.com/tendermint/abci/blob/master/README.md) clearly linked or actually just listed (in the main docs too!) would be immensely helpful."

4) An encouraging statement regarding some of the things that a beginner might find difficult, with some general advice for each potential roadblock.

5) Links to some external resources on relevant topics eg. hexadecimal numbers, byte strings, cryptography/digital signatures, serialization, etc.

6) Suggestions for apps to build that gradually increase in difficulty --- also, if you have the manpower, an email link or a specific slack channel for tendermint beginners to field questions.

**Comment by zramsay** [comment]
can be closed in favour of https://github.com/tendermint/tendermint/issues/544
