### ISSUE TITLE
Job Posting for Website

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint.github.io#53]
Hi @nylira we are looking for a number of positions in Berlin over the next months.  Here is the first one I would like to post, and I just submitted the text to a local job board.  But nice to have it on the website as well.  You can gladly format it all as you see fit, or edit the text.

Thanks!

----

Tendermint is a first-of-its kind Proof-of-Stake consensus engine in development since 2015. It is designed to provide developers maximum control in developing their own business logic in a blockchain setting, while relying on a secure consensus algorithm.

We’re looking for a motivated, experienced Javascript Engineer to work with backend blockchain engineers to develop web applications for novel blockchain applications.

----

Cosmos.network is a project by the core developers of tendermint to launch a highly-secure public blockchain on this technology. We have recently completed a fundraising round and are looking to rapidly expand, mainly centered around Berlin, Toronto, and San Francisco.

Under the umbrella of the cosmos system, we are building a number of custom blockchain apps for various usecases.  This position would first work on building some smaller applications to demonstrate and discover best practices with this platform, with the potential of later participating in developing the UI for the main comsos application.

Your Tasks:

* Develop intuitive web-based interfaces that expose blockchain applications 
* Work closely with backend engineers (in Berlin and remote)
* Give feedback to refine the design of the REST-based API, as well as general functionality
* Provide a basic UI/UX design to your applications
* Work with a remote designer if needed to polish the applications

Your Skills:

* Minimum 3 years experience in web engineering and Single-Page apps.
* Strong proficiency in HTML5/CSS3/JavaScript (ES6)
* Strong experience with Vue (prefered), ReactJS or AngularJS
* Experience with TDD and willingness to write tests
* Good level of English
* Self-motivated and creative

We offer:

* Flexible hours (part-time or full-time)
* Competitive salary
* Stock options
* An environment with plenty of opportunities to learn and innovate
* Exposure to cutting-edge blockchain technology  
* Work on open-source software with chance for more exposure
* Potential to work remotely later on

Sounds good?  Please submit a cover letter and resume to berlin@tendermint.com. Please include availability dates and desired working hours per week.

**Comment by nylira** [comment]
Thanks for the details Ethan! I've updated the site (and homepage) with the listing.
