### ISSUE TITLE
community: Slack link is broken

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint.github.io#91]
On the website under sub-section "Community", the link to Slack is broken, it goes to https://forum.tendermint.com:3000.
<img width="269" alt="screen shot 2017-08-02 at 3 22 29 pm" src="https://user-images.githubusercontent.com/4898263/28895646-762ec698-7796-11e7-81a0-45e466ed4e68.png">

**Comment by adrianbrink** [comment]
This will be changed to rocket chat in the coming days.

**Comment by nylira** [comment]
Fixed

**Comment by odeke-em** [comment]
Awesome, thank you @nylira and @adrianbrink!
